version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/JobBoard
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key
      - HOST=http://localhost:5000
    depends_on:
      - mongo
      - redis
    command: npm start
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
